### PR TITLE
feat: support for increasing and decreasing interval

### LINKED ISSUE #67: [feature-request] Shortcut to increase/decrease the interval
Thanks for this awesome tool. It would be handy to be able to change the interval during runtime. I'm thinking about Ctrl-x for decreasing and Ctrl-a for increasing the interval. What do you think?

### PR DESCRIPTION
**Pull request by arpandaze**
Closes #67

Please let me know if any change is necessary!

### CODE REVIEW

**Comment by sachaos** [comment]
When I specified `-n 100ms` and increase to `600ms`, I couldn't back to `100ms` by decreasing feature.

**Comment by arpandaze** [comment]
That should be because I have set min interval to be 500ms. Also step is 500ms. Maybe step should be configurable from config?

**Comment by sachaos** [comment]
Yes, I think so.

**Comment by arpandaze** [comment]
> Yes, I think so.

I have updated to make interval step and min interval configurable.

**Review by sachaos — APPROVED** [review]
LGTM

**Comment by sachaos** [comment]
Thank you!
I'll fix some code, and release it!

**Pull request merged**
